import { Recipe } from './types'

export const recipes: Recipe[] = [
  {
    id: 'chicken-stir-fry',
    name: 'Chicken Stir Fry',
    tags: ['dairy-free', 'nut-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'chicken breast', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'broccoli', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp', category: 'pantry' },
      { name: 'rice', quantity: 2, unit: 'cup', category: 'pantry' },
    ],
    instructions: ['Cook rice.', 'Stir fry chicken and broccoli.', 'Add soy sauce and serve.'],
  },
  {
    id: 'veggie-tacos',
    name: 'Black Bean Veggie Tacos',
    tags: ['vegetarian', 'nut-free'],
    prepTimeMinutes: 20,
    ingredients: [
      { name: 'black beans', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'corn tortillas', quantity: 8, unit: 'unit', category: 'pantry' },
      { name: 'bell pepper', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'cheddar cheese', quantity: 1, unit: 'cup', category: 'dairy' },
    ],
    instructions: ['Sauté bell peppers.', 'Warm beans.', 'Assemble tacos with cheese.'],
  },
  {
    id: 'lentil-soup',
    name: 'Hearty Lentil Soup',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 35,
    ingredients: [
      { name: 'lentils', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'carrot', quantity: 3, unit: 'unit', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'vegetable broth', quantity: 4, unit: 'cup', category: 'pantry' },
    ],
    instructions: ['Sauté onion and carrot.', 'Add lentils and broth.', 'Simmer 25 minutes.'],
  },
  {
    id: 'salmon-quinoa-bowl',
    name: 'Salmon Quinoa Bowl',
    tags: ['pescatarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'salmon fillet', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'quinoa', quantity: 1, unit: 'cup', category: 'pantry' },
      { name: 'spinach', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'lemon', quantity: 1, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Cook quinoa.', 'Pan-sear salmon.', 'Assemble bowl with spinach and lemon.'],
  },
  {
    id: 'margherita-pizza',
    name: 'Margherita Pizza',
    tags: ['vegetarian', 'nut-free'],
    prepTimeMinutes: 40,
    ingredients: [
      { name: 'pizza dough', quantity: 1, unit: 'unit', category: 'pantry' },
      { name: 'mozzarella', quantity: 200, unit: 'g', category: 'dairy' },
      { name: 'tomato', quantity: 3, unit: 'unit', category: 'produce' },
      { name: 'basil', quantity: 0.25, unit: 'cup', category: 'produce' },
    ],
    instructions: ['Roll out dough.', 'Top with tomato and mozzarella.', 'Bake and add basil.'],
  },
  {
    id: 'beef-tacos',
    name: 'Ground Beef Tacos',
    tags: ['dairy-free', 'nut-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'ground beef', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'corn tortillas', quantity: 8, unit: 'unit', category: 'pantry' },
      { name: 'onion', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'tomato', quantity: 2, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Brown beef with onion.', 'Warm tortillas.', 'Assemble tacos with tomato.'],
  },
  {
    id: 'vegan-buddha-bowl',
    name: 'Vegan Buddha Bowl',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'chickpeas', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'sweet potato', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'kale', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'tahini', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Roast sweet potato and chickpeas.', 'Massage kale.', 'Drizzle with tahini.'],
  },
  {
    id: 'shrimp-pasta',
    name: 'Garlic Shrimp Pasta',
    tags: ['pescatarian', 'nut-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'shrimp', quantity: 400, unit: 'g', category: 'protein' },
      { name: 'pasta', quantity: 300, unit: 'g', category: 'pantry' },
      { name: 'garlic', quantity: 4, unit: 'unit', category: 'produce' },
      { name: 'parmesan', quantity: 0.5, unit: 'cup', category: 'dairy' },
    ],
    instructions: ['Cook pasta.', 'Sauté shrimp with garlic.', 'Toss with pasta and parmesan.'],
  },
  {
    id: 'turkey-chili',
    name: 'Turkey Chili',
    tags: ['dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 40,
    ingredients: [
      { name: 'ground turkey', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'kidney beans', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'tomato', quantity: 4, unit: 'unit', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Brown turkey.', 'Add beans, tomato, onion.', 'Simmer 25 minutes.'],
  },
  {
    id: 'caprese-sandwich',
    name: 'Caprese Grilled Sandwich',
    tags: ['vegetarian', 'nut-free'],
    prepTimeMinutes: 15,
    ingredients: [
      { name: 'sourdough bread', quantity: 4, unit: 'unit', category: 'pantry' },
      { name: 'mozzarella', quantity: 200, unit: 'g', category: 'dairy' },
      { name: 'tomato', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'basil', quantity: 0.25, unit: 'cup', category: 'produce' },
    ],
    instructions: ['Layer bread with mozzarella, tomato, basil.', 'Grill until golden.'],
  },
  {
    id: 'vegan-curry',
    name: 'Chickpea Coconut Curry',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'chickpeas', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'coconut milk', quantity: 1, unit: 'cup', category: 'pantry' },
      { name: 'spinach', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'rice', quantity: 2, unit: 'cup', category: 'pantry' },
    ],
    instructions: ['Cook rice.', 'Simmer chickpeas in coconut milk.', 'Stir in spinach.'],
  },
  {
    id: 'baked-cod',
    name: 'Lemon Baked Cod',
    tags: ['pescatarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'cod fillet', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'lemon', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'asparagus', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Season cod with lemon and oil.', 'Bake with asparagus 20 minutes.'],
  },
  {
    id: 'egg-fried-rice',
    name: 'Vegetable Egg Fried Rice',
    tags: ['vegetarian', 'dairy-free', 'nut-free'],
    prepTimeMinutes: 20,
    ingredients: [
      { name: 'rice', quantity: 3, unit: 'cup', category: 'pantry' },
      { name: 'egg', quantity: 3, unit: 'unit', category: 'protein' },
      { name: 'carrot', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Scramble eggs.', 'Stir fry rice and carrot.', 'Combine with soy sauce.'],
  },
  {
    id: 'stuffed-peppers',
    name: 'Quinoa Stuffed Peppers',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 45,
    ingredients: [
      { name: 'bell pepper', quantity: 4, unit: 'unit', category: 'produce' },
      { name: 'quinoa', quantity: 1, unit: 'cup', category: 'pantry' },
      { name: 'black beans', quantity: 1, unit: 'cup', category: 'pantry' },
      { name: 'tomato', quantity: 2, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Cook quinoa.', 'Mix with beans and tomato.', 'Stuff peppers and bake.'],
  },
  {
    id: 'chicken-caesar-salad',
    name: 'Grilled Chicken Caesar Salad',
    tags: ['nut-free', 'gluten-free'],
    prepTimeMinutes: 20,
    ingredients: [
      { name: 'chicken breast', quantity: 400, unit: 'g', category: 'protein' },
      { name: 'romaine lettuce', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'parmesan', quantity: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Grill chicken.', 'Toss lettuce with oil.', 'Top with chicken and parmesan.'],
  },
  {
    id: 'mushroom-risotto',
    name: 'Creamy Mushroom Risotto',
    tags: ['vegetarian', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 40,
    ingredients: [
      { name: 'arborio rice', quantity: 1.5, unit: 'cup', category: 'pantry' },
      { name: 'mushroom', quantity: 3, unit: 'cup', category: 'produce' },
      { name: 'parmesan', quantity: 0.5, unit: 'cup', category: 'dairy' },
      { name: 'vegetable broth', quantity: 4, unit: 'cup', category: 'pantry' },
    ],
    instructions: ['Sauté mushroom.', 'Add rice and broth gradually.', 'Stir in parmesan.'],
  },
  {
    id: 'pork-stir-fry',
    name: 'Pork and Vegetable Stir Fry',
    tags: ['dairy-free', 'nut-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'pork loin', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'broccoli', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'bell pepper', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Slice pork thin.', 'Stir fry with vegetables.', 'Add soy sauce.'],
  },
  {
    id: 'falafel-wrap',
    name: 'Falafel Wrap',
    tags: ['vegan', 'vegetarian', 'dairy-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'chickpeas', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'tahini', quantity: 2, unit: 'tbsp', category: 'pantry' },
      { name: 'flour tortilla', quantity: 4, unit: 'unit', category: 'pantry' },
      { name: 'tomato', quantity: 2, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Form and fry falafel.', 'Assemble in tortilla with tomato and tahini.'],
  },
  {
    id: 'tuna-poke-bowl',
    name: 'Tuna Poke Bowl',
    tags: ['pescatarian', 'dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 20,
    ingredients: [
      { name: 'tuna', quantity: 400, unit: 'g', category: 'protein' },
      { name: 'rice', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'cucumber', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Cook rice.', 'Cube tuna and marinate in soy sauce.', 'Assemble bowl with cucumber.'],
  },
  {
    id: 'bbq-chicken-flatbread',
    name: 'BBQ Chicken Flatbread',
    tags: ['nut-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'chicken breast', quantity: 300, unit: 'g', category: 'protein' },
      { name: 'flatbread', quantity: 2, unit: 'unit', category: 'pantry' },
      { name: 'cheddar cheese', quantity: 1, unit: 'cup', category: 'dairy' },
      { name: 'bbq sauce', quantity: 3, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Shred cooked chicken and toss in BBQ sauce.', 'Top flatbread and bake with cheese.'],
  },
  {
    id: 'vegetable-fajitas',
    name: 'Vegetable Fajitas',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free'],
    prepTimeMinutes: 20,
    ingredients: [
      { name: 'bell pepper', quantity: 3, unit: 'unit', category: 'produce' },
      { name: 'onion', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'flour tortilla', quantity: 6, unit: 'unit', category: 'pantry' },
      { name: 'black beans', quantity: 1, unit: 'cup', category: 'pantry' },
    ],
    instructions: ['Sauté peppers and onion.', 'Warm beans.', 'Assemble fajitas.'],
  },
  {
    id: 'shrimp-tacos',
    name: 'Baja Shrimp Tacos',
    tags: ['pescatarian', 'nut-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'shrimp', quantity: 400, unit: 'g', category: 'protein' },
      { name: 'corn tortillas', quantity: 8, unit: 'unit', category: 'pantry' },
      { name: 'cabbage', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'lemon', quantity: 1, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Season and cook shrimp.', 'Shred cabbage.', 'Assemble tacos with lemon.'],
  },
  {
    id: 'eggplant-parmesan',
    name: 'Baked Eggplant Parmesan',
    tags: ['vegetarian', 'nut-free'],
    prepTimeMinutes: 45,
    ingredients: [
      { name: 'eggplant', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'mozzarella', quantity: 200, unit: 'g', category: 'dairy' },
      { name: 'tomato', quantity: 3, unit: 'unit', category: 'produce' },
      { name: 'parmesan', quantity: 0.5, unit: 'cup', category: 'dairy' },
    ],
    instructions: ['Slice and bake eggplant.', 'Layer with tomato and cheese.', 'Bake until bubbly.'],
  },
  {
    id: 'steak-and-veggies',
    name: 'Pan-Seared Steak and Vegetables',
    tags: ['dairy-free', 'nut-free', 'gluten-free'],
    prepTimeMinutes: 25,
    ingredients: [
      { name: 'steak', quantity: 500, unit: 'g', category: 'protein' },
      { name: 'asparagus', quantity: 2, unit: 'cup', category: 'produce' },
      { name: 'sweet potato', quantity: 2, unit: 'unit', category: 'produce' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp', category: 'pantry' },
    ],
    instructions: ['Sear steak.', 'Roast sweet potato and asparagus.', 'Rest steak and serve.'],
  },
  {
    id: 'black-bean-burgers',
    name: 'Black Bean Burgers',
    tags: ['vegan', 'vegetarian', 'dairy-free', 'nut-free'],
    prepTimeMinutes: 30,
    ingredients: [
      { name: 'black beans', quantity: 2, unit: 'cup', category: 'pantry' },
      { name: 'burger buns', quantity: 4, unit: 'unit', category: 'pantry' },
      { name: 'onion', quantity: 1, unit: 'unit', category: 'produce' },
      { name: 'tomato', quantity: 2, unit: 'unit', category: 'produce' },
    ],
    instructions: ['Mash beans with onion into patties.', 'Pan-fry patties.', 'Assemble on buns with tomato.'],
  },
]
